web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'localhost'
  environment:
  # admin user: root
  # admin password: set at the first screen load
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://mastervm:8000'
  ports:
    - '8000:8000'
    - '8022:22'
  volumes:
    - '$GITLAB_HOME/config:/etc/gitlab'
    - '$GITLAB_HOME/logs:/var/log/gitlab'
    - '$GITLAB_HOME/data:/var/opt/gitlab'
